window.onload = function() {
	document.getElementById('get-new-date').addEventListener("click", function( event ) {
		newDate();
		cutePic();
	})
}

function newDate() {
  var randomNumber = Math.floor(Math.random() * (dates.length));
  document.getElementById('dateDisplay').innerHTML = dates[randomNumber];
} 
function cutePic() {
	var randomPic	= Math.floor(Math.random() * (pics.length));
	document.getElementById('pic').src = pics[randomPic];
}
var pics = [
	'https://content-na.drive.amazonaws.com/cdproxy/templink/7si4NOkajda9TwV0uqyIEfgZEWMZwpTRK1s_F2XOjEseJxFPc?viewBox=519%2C692',
	'https://content-na.drive.amazonaws.com/cdproxy/templink/ceHPcITCBlyZ0tlSWndZUI_riGtelFL6htuMy7gt2YYeJxFPc?viewBox=432%2C324',
	'https://content-na.drive.amazonaws.com/cdproxy/templink/HyKux8uOe3xYPHStQ185kNRA-e0hXMW1RiePBack-wQeJxFPc?viewBox=487%2C325',
	'http://i843.photobucket.com/albums/zz358/Psiouxee13/IMG_20130418_120801_zpsece1deae.jpg',
	'http://i843.photobucket.com/albums/zz358/Psiouxee13/IMG_20130418_120801_zpsece1deae.jpg',
	'http://i843.photobucket.com/albums/zz358/Psiouxee13/FxCam_1345927001317_zps8a1eeefd.jpg',
	'http://i843.photobucket.com/albums/zz358/Psiouxee13/FxCam_1342315753516_zpsff482eac.jpg',
	'http://i843.photobucket.com/albums/zz358/Psiouxee13/FxCam_1341454662416_zpsddbb78d5.jpg',
	'http://i843.photobucket.com/albums/zz358/Psiouxee13/FxCam_1341454776949_zpse009e11a.jpg',
	'http://i843.photobucket.com/albums/zz358/Psiouxee13/FxCam_1339380768078_zps1d8fa65c.jpg',
	'http://i843.photobucket.com/albums/zz358/Psiouxee13/FxCam_1337563878127_zps97dec647.jpg',
	'http://i843.photobucket.com/albums/zz358/Psiouxee13/2013-01-18_23-18-07_340_zps676230e8.jpg',
	'http://i843.photobucket.com/albums/zz358/Psiouxee13/2013-01-18_23-25-10_862_zpsa292b9ae.jpg',
	'http://i843.photobucket.com/albums/zz358/Psiouxee13/2013-01-18_23-28-06_378_zpse420da6c.jpg',
	'http://i843.photobucket.com/albums/zz358/Psiouxee13/how_is_babby_formed_zps22fd3b08.jpg',
	'http://i843.photobucket.com/albums/zz358/Psiouxee13/P1020679_zps505c301a.jpg',
	'http://i843.photobucket.com/albums/zz358/Psiouxee13/P1020678_zps5c8b6110.jpg',
	'http://i843.photobucket.com/albums/zz358/Psiouxee13/P1020674_zps7b255566.jpg',
	'http://i843.photobucket.com/albums/zz358/Psiouxee13/P1020669_zps4aa945c5.jpg',
	'http://i843.photobucket.com/albums/zz358/Psiouxee13/P1020549_zpsb8af1fd3.jpg',
	'http://i843.photobucket.com/albums/zz358/Psiouxee13/P1020503_zps84b11940.jpg',
	'http://i843.photobucket.com/albums/zz358/Psiouxee13/P1020460_zpsbf7e576e.jpg',
	'http://i843.photobucket.com/albums/zz358/Psiouxee13/P1020453_zpsecb2ba93.jpg',
	'http://i843.photobucket.com/albums/zz358/Psiouxee13/2012-09-08_19-16-57_829_zpse024a7ee.jpg',
	'http://i843.photobucket.com/albums/zz358/Psiouxee13/P1010801_zps080c5cc4.jpg',
	'http://i843.photobucket.com/albums/zz358/Psiouxee13/2012-07-14_19-40-59_163_zps9ac1658a.jpg',
	'http://i843.photobucket.com/albums/zz358/Psiouxee13/2012-07-04_20-08-35_614_zps11c7d9ec.jpg',
	'http://i843.photobucket.com/albums/zz358/Psiouxee13/2012-07-04_20-06-22_30_zps757b3913.jpg'
];

var dates = [
'1. Swing at the park',
'2. Go rock climbing',
'3. Go tubing down a stream',
'4. Build a dam in a stream, then swim or wade',
'5. Take a sunrise hike then have breakfast',
'6. Tip-toe through the sprinklers',
'7. Go on a hike to a local State or National park',
'8. Explore caves',
'9. Make kites and fly them',
'10. Go tree climbing',
'11. Make creations out of dirt or sand',
'12. Go bird watching',
'13. Climb a hill and watch the sunset',
'14. Go fishing',
'15. Go tubing in snow',
'16. Go ice skating',
'17. Walk the canyon trail',
'18. Go waterskiing with a group and have a cookout',
'19. Go boating',
'20. Get several couples and go on a day hike',
'21. Go on a moonlight hike',
'22. Go backpacking',
'23. Play in the sand dunes',
'24. Go ice fishing',
'25. Build a snow fort and have a snowball fight',
'26. Go sledding',
'27. Build a snowman on a park, hospital, or school lawn',
'28. Go ice blocking',
'29. Have a squirt-gun fight',
'30. Go four wheeling or off-roading',
'31. Sing around a campfire and have smores',
'32. Buy KFC and eat it on the water tower',
'33. Build snow sculptures at the dorms or institute',
'34. Feed the birds',
'35. Go on a nature walk. Try to identify flowers',
'36. Go camping with the family',
'37. Visit lakes and ask the tour guides questions',
'38. Build a raft and use it',
'39. Pan for gold',
'40. Drive out to the desert and spell words with rocks',
'41. Make mud pies',
'42. Have a tug-of-war. Try it over a creek',
'43. Roller-skate',
'44. Go sand-surfing',
'45. Hunt',
'46. Target shoot',
'47. Go mountain climbing',
'48. Go rappelling',
'49. Hike to a waterfall and see if you can follow the feeding stream',
'50. Take a geology field trip',
'51. Take the tram to the top of a ski lift in the summer and hike down',
'52. Pick berries and make jelly',
'53. Take a long ride or walk with your date and several little children',
'54. Hunt for fossils',
'55. Spend a survival day in the wilderness',
'56. Visit a state or national park',
'57. Visit a dam on a big river',
'58. Walk in the rain; jump in the puddles',
'59. Go on a moonlight walk',
'60. Have tennis tournament (add breakfast for before school/work)',
'61. Go to an athletic contest at half time',
'62. Go cross country skiing',
'63. Go cycling',
'64. Go horseback riding',
'65. Go to the gym',
'66. Go to a rodeo',
'67. Play tennis at night. Play doubles with others',
'68. Play volleyball',
'69. Go rollerskating/blading/boarding',
'70. Go target shooting with a .22',
'71. Take your date to a game you are playing in',
'72. Play racquetball or croquet',
'73. Go to the local theatre',
'74. Play basketball',
'75. Play mud football or volleyball. Go swimming after to clean off',
'76. Ride a bicycle built for two',
'77. Play hockey in a vacant street',
'78. Ice skate',
'79. Play a football game in the snow',
'80. Snowmobile',
'81. Spend an evening at the gym',
'82. Play hole-in-one in the backyard',
'83. Have a gymnastics contest. Take pictures',
'84. Play handball',
'85. Play three-legged basketball',
'86. Play broom hockey',
'87. Play Frisbee football or golf',
'88. Go golf ball hunting',
'89. Go swimming',
'90. Go canoeing or sailing',
'91. Play water basketball',
'92. Go to the driving range',
'93. Go miniature golfing',
'94. Play soccer',
'95. Play kick the can',
'96. Have a jacks or tiddlywinks tournament',
'97. Play ultimate Frisbee',
'98. Play Ping Pong',
'99. Play Monopoly with another couple',
'100. Play truth or consequences',
'101. Play pool',
'102. Go bowling',
'103. Play hide and seek',
'104. Play games and pop popcorn with background music',
'105. Play hide and seek, tag, or cops on horseback',
'106. Play marbles',
'107. Play Red Rover',
'108. Play Hopscotch',
'109. Jump rope. Don’t forget the rhymes',
'110. Play Cowboys and Indians',
'111. Play Four squares',
'112. Play Run, sheep, run',
'113. Play Fox and geese',
'114. Play Freeze tag',
'115. Play Statues',
'116. Play Cops and robbers',
'117. Find words in license plates, or find the alphabet in order',
'118. Puzzles, put one together or make your own',
'119. Play “around the ping-pong table”',
'120. Play water balloon basketball',
'121. Play water balloon volleyball or feather volleyball',
'122. Play checkers or chess in the park or on a rock in the mountains',
'123. play board games with your date’s family',
'139. Paint a barn door or a house',
'140. Organize your junk drawer',
'141. Bottle fruit',
'142. Entertain at hospitals or care centers',
'143. Tie a quilt',
'144. Read to a blind person',
'145. Paint a room together',
'146. Prepare holiday treats and take them to the hospital or care center',
'147. Make cookies and deliver them to a widow or a friend having a birthday',
'148. Re-shingle a roof',
'149. Wallpaper a bedroom',
'150. Wash a car, tune the engine, clean the inside and outside of a car. Have a water fight afterwards',
'151. Plant or harvest a garden',
'152. Refinish a desk or other furniture',
'153. Organize a Sub for Santa. Wrap and deliver the presents together',
'154. Feed the cows together',
'155. Clean the garage',
'156. Write to missionaries',
'157. Write a thank you note to your Bishop',
'158. Visit a rest home. Read or sing to them. Ask them to tell you stories',
'159. Visit children in a hospital and read to them if allowed',
'160. Rake leaves or shovel snow for someone in need',
'161. Run errands for your parents, take your date',
'162. Baby-sit a relative’s children (Good test for both of you)',
'163. Gather a load of firewood for you parents or neighbor',
'164. Pick and bottle or dry fruit',
'165. Help someone rearrange their furniture',
'166. Make holiday decorations and deliver them to a hospital or rest home',
'167. Clean the fridge and eat leftovers',
'168. Change a tire or work on a car together',
'169. Dress up as Mr. and Mrs. Claus and go to the children’s hospital (or just walk up and down the street)',
'170. Have a shoe-shining party',
'171. Bake cookies and take them to a parking attendant or a ticket seller at a theater',
'172. Wrap presents for older people and leave them on their door step; ring the bell and run',
'173. Frost graham crackers and take them to someone',
'174. Build a clubhouse for neighborhood kids',
'175. Take a family member to a ballgame',
'176. Pass out bubblegum on Main Street',
'177. Go shopping for a family member',
'178. Help a sheepherder sheer his sheep',
'179. Have a pet show with kids in the neighborhood and award prizes',
'180. Learn magic tricks and put on a show for the neighborhood kids',
'181. Help a farmer take care of his animals',
'182. Bake notes into cookies and send them to people',
'183. Paint addresses on curbs',
'184. Paint house trim for a neighbor',
'185. Go bug collecting',
'186. Take a sight-seeing tour of your city',
'187. Plan a pretend trip',
'188. Have a spa day',
'189. Color in coloring books',
'190. Have a bubble blowing contest (gum or bubble blow)',
'191. Go to a free concert',
'192. Study together',
'193. Read a funny children’s book together',
'194. Gather pine nuts',
'195. Go arrowhead hunting',
'196. Plan a street dance (Permit required)',
'197. Build a rope swing and play on it',
'198. Go window shopping',
'199. Picture-taking',
'200. A valley-wide treasure hunt',
'201. Visit a City Council or school board meeting',
'202. Visit the observatory',
'203. Tour the county jail',
'204. Color Easter Eggs',
'205. Go to a school play',
'206. Go to the county fair',
'207. Read a book together and discuss it',
'208. Make crafts, or mold clay',
'209. Christmas Caroling party',
'210. A barn dance',
'211. Finger-painting. Try it with your toes',
'212. Make posters to advertise an activity at a church or school',
'213. Make a spook house for Halloween',
'214. Have a talent show',
'215. Visit your date’s Grandparents and take along a tape and ask them to tell you about dating in the good ol’ days',
'216. Go looking for furniture in furniture stores',
'217. Look at family or childhood pictures',
'218. Read a Book of Remembrance together',
'219. Have a cabin party with eats, games, and movies',
'220. Watch people and airplanes at the airport',
'221. Go shopping and buy a cheap surprise for each other',
'222. Go to an institute dance',
'223. Teach a boy to dance',
'224. Make jerky out of a deer roast',
'225. Go trick or treating for Halloween, Or anytime',
'226. Take a survey you have made up or an opinion poll',
'227. Show movies or slides of your childhood days',
'228. Pretend you are engaged and go test drive cars, try on rings, and check out apartments',
'229. Gather rocks and identify them. Also, try polishing them',
'230. Visit a cemetery. Show your date your family plot',
'231. Park down town and observe people',
'232. Try archery',
'233. Park and listen to the Mystery Theater',
'234. Geocaching',
'235. Catch caterpillars and watch them turn into butterflies',
'236. Get a permit and chop down your own Christmas tree',
'237. Dry flowers in a microwave and arrange them',
'238. Try knitting',
'239. Go grocery shopping',
'240. Go Christmas shopping - regardless of what time of the year it is',
'241. Bake cakes. Decorate them blindfolded',
'242. Whipping cream or shaving cream fight. Be sure to dress for it (or go to the river and do it there)',
'243. Draw pictures of each other',
'244. Style each other’s hair. Put makeup on each other',
'245. Cut out pictures from a magazine. Tell a story with them',
'246. Hunt for four-leaf clovers. Make wishes',
'247. GROUP DATE - rent a limo and go on a cliche date',
'248. Go on a Grimm Ghost Tour',
'249. Dress up like a gangster and kidnap your date. Take them out for dinner and old movies',
'250. Have a cheerleader tryout; make up cheers and routines',
'251. Go to a Disney movie in a Disney costume',
'252. Send your date an anonymous reserved seat ticket to some event and when they arrive, sit down next to them',
'253. Have yourself delivered to your date in a box',
'254. Go on a date where you don’t spend more than $1.00',
'255. Be clowns in a parade',
'256. Have a paper-airplane contest',
'257. Go to the pool or beach in an old fashioned swimsuit',
'258. Find a place with an echo and have a jam session',
'259. Have a hula hoop contest',
'260. Play five-step with a football. Kick the ball back and forth. Each time you catch it you move five steps closer to the other person’s goal',
'261. Have a knot tying contest (for knots to tie, look in the Boy Scout handbook)',
'262. Have a grass fight or a fall leaf fight',
'263. Build a tree house',
'264. Figure out some April Fools pranks',
'265. Ride in a horse drawn sleigh',
'266. Try walking on stilts',
'267. Watch Sesame Street, Mr. Rogers Neighborhood, or Saturday Morning cartoons on TV',
'268. Write to Santa',
'269. Make soap sculptures',
'270. Build a model plane or car',
'271. Cut dolls or snowflakes out of paper, or try origami',
'272. Collect recyclable bottles to buy penny candy',
'273. Arm wrestle, thumb wrestle, Indian leg wrestle',
'274. Have a Jell-O fight',
'275. Play on a trampoline',
'276. Visit Indian ruins',
'277. Go early to a parade and fix breakfast and play games while you wait',
'278. Skip stones on a lake',
'279. Dodge sprinklers on campus',
'280. Go snipe hunting',
'281. Watch clouds and identify shapes',
'282. Go canoeing in the moonlight',
'283. Take a tractor ride at a farm',
'284. Go for a drive without destination in mind. Stop at places that look interesting',
'285. Hunt for wildflowers. Have field guide to identify them',
'286. Have an Easter Egg hunt',
'287. Try to catch a greased pig',
'288. Hunt for night crawlers together',
'290. Count satellites',
'291. Have a road rally where you switch between navigating and driving the course',
'292. Catch butterflies and start a collection',
'293. Play computer games',
'294. Watch passing cars. Each person chooses a color. See who can count the most in their color',
'295. Visit a cemetery. Look at old names and dates and make up stores about the people',
'296. Act like a tourist in your own town',
'297. Drive to another town for dinner',
'298. Go to a garage or rummage sale or bazaar',
'299. Read magazines together at the library',
'300. Go to a drug store and read all the greeting cards. Buy one for her parents',
'301. Visit a TV, radio or movie studio',
'302. Go to a store and play The Price is Right. Take turns guessing the prices of items. Prizes for the winner',
'303. Visit historical sights',
'304. Visit a police station or a fire station',
'305. Using a clipboard, go to a fair and act like a judge',
'306. Fly electronic airplane models',
'307. Go to a stock-car race',
'308. Visit a humane shelter or an animal hospital (buy a dog or cat if desired)',
'309. Attend the ballet, a symphony concert, the opera, or theater',
'310. Take dance lessons',
'311. Attend the circus',
'312. Attend an ice show',
'313. Attend a demolition derby',
'314. Visit a water treatment facility',
'315. Visit a newspaper or other printing plant',
'316. Visit a milk-processing plant',
'317. Visit a bakery',
'318. Visit a sewage-processing plant',
'319. Word searches, crossword puzzles, dot-to-dots, etc.',
'320. Have a smile contest',
'321. Make up captions for pictures in family albums',
'322. Read the newspaper together. Include the kids section and the comics. Pick your favorite item out of the want ads. Shop for groceries from the ads',
'323. Watch a cultural presentation on TV',
'324. Discuss current events',
'325. Cut out pictures from ads, hide the product and try to guess what is being advertised',
'326. Play the commercial game',
'327. Read your grandparent’s or other ancestor’s journal',
'328. Play the piano and sing together',
'329. Get a load of firewood and cut logs for the fireplace',
'330. Put notes in helium balloons and set them loose',
'331. Go through a catalogue and pick items out to learn about each other’s tastes',
'332. Pick a historical figure and learn about them together',
'333. Go to a lecture and discuss it',
'334. Have a popcorn-sculpting contest',
'335. If you date a school teacher, help them grade papers',
'336. Pretend to be an interior decorator and plan the interior of your future home',
'337. Exchange white elephant gifts',
'338. Design your dream house',
'339. Decorate your date’s room',
'340. Have a tall-tale contest, the winner gets a prize',
'341. Cut up a newspaper and make a story about your date with the pieces',
'342. Show slide or pictures of vacations, or world wide adventures',
'343. Send an invitation to a date in balloons-each balloon has a note, but only one has the invitation',
'344. Go on a safari: set up a tent in your front room with all the plants you can find',
'345. Plant and care for flowers',
'346. Do yard work',
'347. Scrub and wax floors',
'348. Vacuum or dust',
'349. Go to junk stores find something unusual and fix it up',
'350. Build something together. Legos? cardboard fort? something out of wood?',
'351. Put together an ant farm',
'352. learn something new together',
'353. make a scrapbook page of the last fun thing we did',
'354. Build a crystal radio',
'355. Landscape a yard',
'356. Do the wash in a Laundromat',
'357. Work together on a research paper',
'358. Usher at a symphony or other civic event',
'359. Train the pups: new tricks',
'360. Break a horse',
'361. Repair a bike',
'362. Learn a new talent or craft at a hobby shop',
'363. Make a terrarium',
'364. Make candles',
'365. Make holiday decorations',
'366. Make Valentines',
'367. Make puppets and put on a show',
'368. Create a homemade band',
'369. Develop film in a darkroom',
'370. cover a song with only kazoos',
'371. teach each other something new',
'372. Create a new food recipe',
'373. Sew matching shirts',
'374. Pottery',
'375. Do Macrame or a string design',
'376. Make mobiles',
'377. Do fly-typing',
'378. Paint-by-number',
'379. Go to an old folks dance – remember the foxtrot and the waltz?',
'380. Try a new sport together',
'381. Try some musical duets',
'382. Be the test subjects at a beauty school',
'383. Have an ice cream sculpting contest',
'384. Play the alphabet game in an art museum with things in the paintings',
'385. Go on a tandem bike ride',
'386. Go to a cemetery at night and talk',
'387. Go to a store and fill carts with a variety of stuff. Then regroup and switch baskets. The first team to return the stuff to their proper place wins a prize',
'388. Have an audio or photo scavenger hunt. Have a list of sounds or scenes and send groups out with a recorder or disposable camera (try having a time limit)',
'389. Go to DI. Give each person $5 to buy an outfit. They wear that the rest of the date',
'390. Fill out internet quizzes together. how well do you know me, etc.',
'391. Go to the zoo',
'392. Go to the Planetarium',
'393. GROUP DATE- Give each couple $1 and go buy something for dinner. Regroup and put it all together',
'394. GROUP DATE- Play softball',
'395. GROUP DATE- Play flag football',
'396. GROUP DATE- Play ultimate Frisbee',
'397. GROUP DATE- Double with your parents',
'398. GROUP DATE- Make a movie then watch it',
'399. GROUP DATE- Have a treasure hunt in a park. End up at a campfire for special goodies',
'400. GROUP DATE- Go on a hayride',
'401. GROUP DATE- Have a hat party. Try making your own hats',
'402. GROUP DATE- Have a party where Santa gives out presents to all',
'403. GROUP DATE- Have a dinner party. Have everyone help cook. Provide aprons and recipes',
'404. GROUP DATE- Have a pumpkin carving contest. Display them afterwards',
'405. GROUP DATE- Built a float for Homecoming or some other parade',
'406. GROUP DATE- Have a backwards party. Do everything backwards',
'407. GROUP DATE- Buy a coloring book and color at an ice cream parlor; have a stranger judge your work',
'408. GROUP DATE- Have a pirate party. Have a treasure map with treasure at the end',
'409. GROUP DATE- Have a blindfold dance',
'410. GROUP DATE- Have an outdoor square dance',
'411. GROUP DATE- Have a star party. Get several telescopes and locate constellations',
'412. GROUP DATE- Play Charades',
'413. GROUP DATE- Play TV game shows: The Price is Right, Hollywood Squares, Deal or No Deal, Jeopardy, Family Feud',
'414. GROUP DATE- Play To Tell the Truth: Each person passes in five funny but true experiences, the head person picks three people. Each of the three gives his version of the story and the group tries to identify the right one',
'415. GROUP DATE- Have a Sadie Hawkins dance or party',
'416. GROUP DATE- Have a pot-luck dinner',
'417. GROUP DATE- Have a group dinner where everyone brings their favorite food. Don’t tell what it is, but a have a rhyme about it. The rhymes are drawn out of a hat. The group guesses what it is. Eat the items in the order they are drawn',
'418. GROUP DATE- Have a number’s dinner. Each item is represented by a number on the menu. The food is eaten in the order the numbers are chosen.',
'419. GROUP DATE- Invite several couples over. Have them bring their favorite recipe. Prepare them together',
'420. Make your own farmers market style yardsale! Get Christina to sell her produce, and make cool things to sell.',
'421. GROUP DATE- Have a “come as you are” party. Call the couples around the dinner time the night before the dinner. Have them come in what they were wearing',
'422. Picnic at your own house',
'423. Take a sunrise hike and have breakfast',
'424. Go on a hike and cook dinner in the mountains',
'425. Go to the aquarium',
'426. Make taffy or honey candy. Pull it and eat it',
'427. Make bread',
'428. Have a waffle supper',
'429. Roast hot dogs and marshmallows',
'430. Make homemade ice cream',
'431. Feed some ducks',
'432. Make donuts',
'433. Make pizza together from scratch - use unusual toppings',
'434. Have a Dutch over cookout',
'435. Have a BBQ and play games at a park',
'436. Prepare and share a candlelight dinner',
'437. Make tinfoil dinners up the canyon',
'438. Walk to an ice cream shop',
'439. Try a reverse dinner. Dessert first',
'440. Have a progressive dinner going from one room to another. Decorate each room differently',
'441. Dress up elegantly and go someplace very inexpensive for dinner',
'442. Have a fondue party',
'443. Have dinner on a card table in a school parking lot',
'444. Fix a meal for your date and his/her parents',
'445. go for a picnic to a ghost town',
'446. Have an international dinner party',
'447. Go bowling until midnight and have breakfast afterwards',
'448. Find a candy recipe and make it together',
'449. Have a formal dinner followed by a Rook tournament',
'450. Have a dress-up formal dinner complete with waiters and violins (have your friends help) serve hamburgers',
'451. Use your imagination in having dinner in the following places: McDonald’s, mountains or hill, back of a pick-up or car, card table at your school, yacht club, barn, tent, semi-trailer, “deserted island”, golf course, under a waterfall, tree house, snow covered mountain, giant tree, appliance box, empty swimming pool',
'452. Have a luau',
'453. Have a corn roast',
'454. Have a backyard BBQ and lawn games',
'455. Try waffles with lots of different toppings or ingredients',
'456. Have dinner at a hospital snack bar (in provo)',
'457. Have a Chinese dinner, with chopsticks and fortune cookies. Sit on the floor',
'458. Have a hobo dinner: cook everything in one pot and eat out of empty tin cans',
'459. Choose a time-period and dress appropriately for dinner',
'460. Choose several hamburger places. Buy one thing from each place and eat at a park',
'461. Have a mixed up dinner, the menu in riddles, food in strange sizes and colors',
'462. Have a dinner with all the food and decorations the same color',
'463. Have a dinner in a field and eat pork and beans from the can',
'464. Have a pizza decorating contest',
'465. Have a vegetarian party',
'466. Prepare a Passover feast',
'467. Roast marshmallows on toothpicks over a candle',
'468. Prepare banana splits',
'469. go to the farmers market',
'470. Have a Western dinner, with beef stew and biscuits. Prepare a mess kit for each guest.',
'471. Have a miniature dinner on doll plates. Cornish game hen, little gelatin molds, birthday candles for a centerpiece, little pies',
'472. Go to the supermarket and give each person $1 or $2. Have them buy their favorite food without letting the others see. Take them home to share', 
'473. Do a scavenger hunt in which you have to get ingredients for your dinner',
'474. Take them home and share all of your childhood memories with them',
'475. Go hot tubbing',
'476. Go to some natural hot springs',
'477. Take a day trip out of state',
'478. Go to a bookstore and have them pick out their favorite books by categories (missed childhood memory, future, etc…)',
'479. Find little unknown restaurants to eat at',
'480. Conduct science experiments (mentos and coke)',
'481. Take a class together',
'482. Pick some Fruit like at a cherry orchard',
'483. Go play at a park',
'484. Do something together neither one has ever done',
'485. Take fake wedding pictures',
'486. Plan a weekend together with a huge group of friends',
'487. Take a Segway-Riding Tour',
'488. Build a home out of cardboard boxes',
'489. Have your own dance party',
'490. Nintendo games night',
'491. Go to the dollar theatre',
'492. Go on a date that you like, even if its not my favorite',
'493. Go salsa dancing',
'494. Go to an arcade',
'495. Make up recipes and eat them',
'496. Visit all the local temples together',
'497. Go to the mall and just walk around',
'498. Look in the paper for free events and attend all you can in one day',
'499. Buy plain shirts and make each other a shirt for the date',
'500. Go for a walk',
'501. Go to a jazz club',
'502. Get couples massages',
'503. take a dance class',
'504. go to a trivia night',
'505. GROUP DATE - play soccer',
'506. Take a day trip to a nearby city you have never been to',
'506. fun-triathalon: we each make a list of the things we like to and try to do our lists as quickly as possible. Record how long it takes so we can break our record in future attempts.',
'507. Go bird watching',
'508. Go to an improv class',
'509. Go to a drive-in movie',
'510. Go on a picnic in a new place',
'511. Have a food sculpture competition. Each of you buy a variety of food and the other has to sculpt with it',
'512. Get our fortunes told! Find a fortune teller or tarot card reader.',
'513. Make me a mixtape: make each other a playlist',
'514. Watch Adventure Time!!!',
'515. Finally finish Donkey Kong 3',
'516. Give me a makeover! Choose my clothes, do my makeup and do my hair',
'517. Grab some popcorn and read the Craigslist missed connection section.',
''
  
];
